ALTER TABLE dados_tse.recurso
  ADD COLUMN IF NOT EXISTS last_probed_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS last_enriched_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS etag TEXT,
  ADD COLUMN IF NOT EXISTS local_path TEXT;